name = "STD-NMR-Analysis"
uuid = "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
authors = ["Abdullah Yasir"]
version = "1.0.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
NMRTools = "f94341a9-f70f-4b16-97f6-9d8ae8b5f8a1"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
julia = "1.6"
Plots = "1"
StatsPlots = "0.15"
ColorSchemes = "3"
CSV = "0.10"
LsqFit = "0.13"
Measurements = "2"
Clustering = "0.15"
Colors = "0.12"
Distances = "0.10"
StatsBase = "0.33"
